FROM python:3.8-slim-buster

WORKDIR /broker

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt


VOLUME /broker/db
COPY . .

ARG PORT

EXPOSE $PORT

CMD ["python3", "app.py", "--port=$PORT"]